databases:
  - name: truthstamp-db
    plan: free

services:
  - type: web
    name: truthstamp-api
    env: docker
    dockerfilePath: docker/api.Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: TRUTHSTAMP_MAX_MB
        value: "25"
      - key: TRUTHSTAMP_JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://truthstamp-web.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: truthstamp-db
          property: connectionString
      - key: TRUTHSTAMP_ADMIN_API_KEY
        generateValue: true
      - key: SMTP_HOST
        value: ""
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: ""
      - key: SMTP_PASS
        value: ""
      - key: SMTP_FROM
        value: "TruthStamp <no-reply@truthstamp.local>"

  - type: web
    name: truthstamp-web
    env: node
    rootDir: web
    plan: free
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://truthstamp-api.onrender.com
